name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: "Build"
        run: zig build --release=safe

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: zig-out/bin/censor-ls

      - uses: actions/checkout@v3
      - name: Set up yq
        shell: bash
        run: |
          sudo curl -fL "https://github.com/mikefarah/yq/releases/download/v4.30.6/yq_linux_amd64" -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
      - name: Compile
        shell: bash
        run: |
          zip -r registry.json.zip registry.json
          sha256sum registry.json registry.json.zip > checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          fail_on_unmatched_files: true
          generate_release_notes: false
          files: |
            registry.json.zip
            checksums.txt
